version: 2

updates:
  - package-ecosystem: nuget
    target-branch: develop
    directory: /
    schedule:
      interval: weekly
      day: wednesday
    commit-message:
      prefix: NuGet packages
    labels: [dependencies]
    assignees: [beauchama]
    groups:
      analyzers:
        patterns:
          - '*Analyzers'
          - SonarAnalyzer.CSharp
          - AsyncFixer
      deps:
        patterns:
          - '*'
        exclude-patterns:
          - '*Analyzers'
          - SonarAnalyzer.CSharp
          - AsyncFixer
          - NSubstitute
          - TUnit
      tests:
        patterns:
          - NSubstitute
          - TUnit

  - package-ecosystem: dotnet-sdk
    target-branch: develop
    directory: /
    schedule:
      interval: weekly
      day: wednesday
    commit-message:
      prefix: .NET SDK
    labels: [dependencies]
    assignees: [beauchama]
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-major', 'version-update:semver-minor']

  - package-ecosystem: github-actions
    target-branch: develop
    directory: /
    schedule:
      interval: weekly
      day: wednesday
    commit-message:
      prefix: GitHub Actions
    labels: [dependencies]
    assignees: [beauchama]
    groups:
      actions:
        patterns:
          - '*'
