name: Staging

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths: [ 'src/KappaDuck.Quack/**', '.github/workflows/staging.yml' ]

permissions:
  contents: read
  checks: write

jobs:
  build:
    name: Build/Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Get version
        shell: pwsh
        run: |
          $date = Get-Date -Format "yyyyMMddHHmmss"
          echo "date=$date" >> $env:GITHUB_ENV

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.x

      - name: Setup Docker
        uses: docker/setup-buildx-action@v3

      - name: Install SDL dependencies
        run: dotnet .\SDL3\build.cs

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration release --no-restore

      - name: Package
        run: dotnet pack --no-build --no-restore --output ./artifacts --version-suffix alpha.${{ env.date }}

      - name: Publish to NuGet
        run: dotnet nuget push "**/*.nupkg" --source https://apiint.nugettest.org/v3/index.json --api-key ${{ secrets.NUGET_STAGING_API_KEY }} --skip-duplicate
